export const TICTACTOE_PLAYER_1 = 'PLAYER_1';
export const TICTACTOE_PLAYER_2 = 'PLAYER_2';

export const TICTACTOE_STATUS_DRAW = 'TICTACTOE_STATUS_DRAW';
export const TICTACTOE_STATUS_RUNNING = 'TICTACTOE_STATUS_RUNNING';
export const TICTACTOE_STATUS_PLAYER1WIN = 'TICTACTOE_STATUS_PLAYER1WIN';
export const TICTACTOE_STATUS_PLAYER2WIN = 'TICTACTOE_STATUS_PLAYER2WIN';
